name: "Bug Report"
description: File a bug report
title: "[BUG]: "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug. Please fill in the details below.
  - type: input
    id: summary
    attributes:
      label: Summary
      description: Provide a one-line summary of the issue.
      placeholder: Login button freezes the page
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Describe the steps to reproduce the problem.
      placeholder: |
        1. Go to the login page
        2. Enter credentials
        3. Click the login button
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Redirect to the dashboard after login
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Page freezes and error appears in console
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Provide details about your environment.
      placeholder: |
        - OS: macOS 14.5
        - Browser: Chrome 115
        - App Version: v1.2.0
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Logs / Screenshots
      description: If applicable, add logs or screenshots.
      placeholder: Paste error message or attach screenshot
    validations:
      required: false
