name: "Feature Request"
description: Suggest a new feature or improvement
title: "[FEAT]: "
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting an idea! Please provide the details below.
  - type: input
    id: summary
    attributes:
      label: Summary
      description: Provide a one-line summary of your request.
      placeholder: Add dark mode support
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem are you trying to solve?
      placeholder: Using the app at night causes eye strain
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution.
      placeholder: Add a dark mode toggle in settings
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered other alternatives?
      placeholder: Relying on browser dark mode, but it's not sufficient
    validations:
      required: false
  - type: textarea
    id: extra
    attributes:
      label: Additional Context
      description: Add any other context, references, or screenshots.
      placeholder: Links, design sketches, or related examples
    validations:
      required: false
