spring:
  advice:
    ignore-url-pattern-list: /v*/api-docs,/docs/**,/swagger-resources/**,/swagger-ui.html,/webjars/**,/swagger/**

  ResponseAdvice / ?????? ?? url ?? ??
  ?? ? ???
  ?? ? ???
  ??? ??? ??? ??
  ? ??? ?? ??